# Imports

In [ ]:
import numpy as np

# Task 1
## Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


# Task 2
## Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
x = np.zeros((3, 3), dtype=np.uint8)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# Task 3
## Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
x = np.random.randint(1, 10, size=(5, 5), dtype=np.uint8)
print(x)

[[7 7 7 2 1]
 [5 7 8 6 1]
 [2 8 9 7 7]
 [2 3 5 1 3]
 [1 2 4 3 4]]


# Task 4
## Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
size = (4, 4)
x = np.random.random_sample(size)
print(x)

[[0.62410511 0.30579083 0.97765869 0.42785942]
 [0.35892378 0.6461913  0.97774972 0.00251374]
 [0.5178693  0.93623583 0.07940717 0.53476766]
 [0.03583657 0.39429989 0.31662285 0.5100528 ]]


# Task 5
## Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
size = (5,)
range = 1, 10

x1 = np.random.randint(*range, size)
x2 = np.random.randint(*range, size)

# x1
print('x1')
print(x1)
print('\n')

# x2
print('x2')
print(x2)
print('\n')

# add
print('add')
print(np.add(x1, x2))
print('\n')

# subtract
print('subtract')
print(np.subtract(x1, x2))
print('\n')

# multiply
print('multiply')
print(np.multiply(x1, x2))
print('\n')

# divide
print('divide')
print(np.divide(x1, x2))
print('\n')

x1
[8 3 1 1 7]


x2
[6 7 5 6 4]


add
[14 10  6  7 11]


subtract
[ 2 -4 -4 -5  3]


multiply
[48 21  5  6 28]


divide
[1.33333333 0.42857143 0.2        0.16666667 1.75      ]




# Task 6
## Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
size = (7,)
range = 1, 10

x1 = np.random.randint(*range, size)
x2 = np.random.randint(*range, size)

# x1
print('x1')
print(x1)
print('\n')

# x2
print('x2')
print(x2)
print('\n')

# dot product
print('dot product')
print(np.dot(x1, x2))
print('\n')

x1
[2 2 1 3 9 2 5]


x2
[2 2 1 3 9 2 5]


dot product
114




# Task 7
## Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
range = 1, 10

x1 = np.random.randint(*range, (2, 2))
x2 = np.random.randint(*range, (2, 3))

# x1
print('x1')
print(x1)
print('\n')

# x2
print('x2')
print(x2)
print('\n')

# dot product
print('dot product')
print(np.dot(x1, x2))
print('\n')

x1
[[8 5 8]
 [7 7 5]]


x2
[[8 5 8]
 [7 7 5]]


dot product
[[77 56 71]
 [73 64 59]]




# Task 8
## Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
range = 1, 10
size = (3, 3)

x = np.random.randint(*range, size)

# x
print('x')
print(x)
print('\n')

# inverse
print('inverse')
print(np.linalg.inv(x))
print('\n')

x
[[7 3 3]
 [9 9 7]
 [7 4 8]]


inverse
[[ 0.27848101 -0.07594937 -0.03797468]
 [-0.14556962  0.22151899 -0.13924051]
 [-0.17088608 -0.0443038   0.2278481 ]]




# Task 9
## Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
size = (4, 4)
x = np.random.random_sample(size)

# x
print('x')
print(x)
print('\n')

# transposed
print('transposed')
print(x.T)
print('\n')

x
[[0.53463288 0.70174183 0.42783221 0.64217363]
 [0.50351128 0.83016932 0.78885667 0.12842365]
 [0.82336224 0.10854651 0.47637393 0.74570832]
 [0.836619   0.15305739 0.83650758 0.17217428]]


transposed
[[0.53463288 0.50351128 0.82336224 0.836619  ]
 [0.70174183 0.83016932 0.10854651 0.15305739]
 [0.42783221 0.78885667 0.47637393 0.83650758]
 [0.64217363 0.12842365 0.74570832 0.17217428]]




# Task 10
## Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
range = 1, 10

x1 = np.random.randint(*range, (3, 4))
x2 = np.random.randint(*range, (4))

# x1
print('x1')
print(x1)
print('\n')

# x2
print('x2')
print(x2)
print('\n')

# dot product
print('dot product')
print(np.dot(x1, x2))
print('\n')

x1
[[8 2 5 3]
 [4 6 2 7]
 [2 8 3 8]]


x2
[5 9 2 1]


dot product
[71 85 96]




# Task 11
## Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
range = 1, 10

x1 = np.random.random_sample((2, 3))
x2 = np.random.random_sample((3))

# x1
print('x1')
print(x1)
print('\n')

# x2
print('x2')
print(x2)
print('\n')

# dot product
print('dot product')
print(np.dot(x1, x2))
print('\n')

x1
[[0.45631187 0.65786813 0.99368822]
 [0.73788767 0.76821367 0.24631152]]


x2
[0.05766791 0.11770907 0.40184   ]


dot product
[0.50305527 0.23195597]




# Task 12
## Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
range = 1, 10
size = (2, 2)

x1 = np.random.randint(*range, size)
x2 = np.random.randint(*range, size)

# x1
print('x1')
print(x1)
print('\n')

# x2
print('x2')
print(x2)
print('\n')

# multiply
print('multiply')
print(np.multiply(x1, x2))
print('\n')

x1
[[6 1]
 [3 6]]


x2
[[6 5]
 [7 9]]


multiply
[[36  5]
 [21 54]]




# Task 13
## Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
range = 1, 10
size = (2, 2)

x1 = np.random.randint(*range, size)
x2 = np.random.randint(*range, size)

# x1
print('x1')
print(x1)
print('\n')

# x2
print('x2')
print(x2)
print('\n')

# dot product
print('dot product')
print(np.dot(x1, x2))
print('\n')

x1
[[5 5]
 [1 7]]


x2
[[6 7]
 [2 5]]


dot product
[[40 60]
 [20 42]]




# Task 14
## Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
range = 1, 100
size = (5, 5)

x = np.random.randint(*range, size)

# x
print('x')
print(x)
print('\n')

# sum
print('sum')
print(np.sum(x))
print('\n')

x
[[98 61 61 37 42]
 [98 54 85 99 39]
 [ 9 66  8  6 14]
 [57 40 17 34 24]
 [23 39 27 96 24]]


sum
1158




# Task 15
## Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
size = (4, 4)
range = 1, 10

x1 = np.random.randint(*range, size)
x2 = np.random.randint(*range, size)

# x1
print('x1')
print(x1)
print('\n')

# x2
print('x2')
print(x2)
print('\n')

# subtract
print('subtract')
print(np.subtract(x1, x2))
print('\n')

x1
[[7 3 8 6]
 [2 1 6 9]
 [2 5 2 6]
 [6 1 5 7]]


x2
[[6 5 2 5]
 [1 9 9 7]
 [7 7 6 4]
 [5 4 9 5]]


subtract

[[ 1 -2  6  1]
 [ 1 -8 -3  2]
 [-5 -2 -4  2]
 [ 1 -3 -4  2]]




# Task 16
## Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [150]:
size = (3, 3)
x = np.random.random_sample(size)

# x
print('x')
print(x)
print('\n')

# sum
print('sum')
print(np.array(
[[np.sum(x[0:1])],
[np.sum(x[1:2])],
[np.sum(x[2:3])]]
))
print('\n')

x
[[0.44087952 0.30842615 0.57296867]
 [0.64409579 0.26467192 0.69239007]
 [0.55151193 0.34990476 0.42905554]]


sum
[[1.32227434]
 [1.60115777]
 [1.33047223]]




# Task 17
## Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [154]:
range = 1, 100
size = (3, 4)

x = np.random.randint(*range, size)

# x
print('x')
print(x)
print('\n')

# sqr
print('sqr')
print(np.multiply(x, x))
print('\n')

x
[[ 8 48 84 31]
 [42 54 73 92]
 [10 73 12 17]]


sqr
[[  64 2304 7056  961]
 [1764 2916 5329 8464]
 [ 100 5329  144  289]]




# Task 18
## Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [156]:
range = 1, 50
size = (4)

x = np.random.randint(*range, size)

# x
print('x')
print(x)
print('\n')

# sqrt
print('sqrt')
print(np.sqrt(x))
print('\n')

x
[14 41 23  7]


sqrt
[3.74165739 6.40312424 4.79583152 2.64575131]


